language: generic
sudo: required

services:
- docker

before_install:
- docker build -t shinyhero .
- docker run --rm shinyhero:latest --name test

#script:
#- docker exec test R -f run_tests.R

#after_script:
#- docker rm -f test
  
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: shinyhero-test
