language: r

services: 
  - docker
  
before_install:
  - docker build -t shinyhero .

script: 
  - docker run --rm shinyhero
  
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: shinyhero-test
