language: r

services: 
  - docker
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t shinyhero .

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: shinyhero-test
